framework:
    mailer:
        dsn: '%env(MAILER_DSN)%'
        envelope:
            sender: 'saasync by Koalati <noreply@koalati.com>'
        headers:
            from: 'saasync by Koalati <noreply@koalati.com>'
