framework:
    mailer:
        dsn: '%env(MAILER_DSN)%'
        envelope:
            sender: 'magicrr by Koalati <noreply@koalati.com>'
        headers:
            from: 'magicrr by Koalati <noreply@koalati.com>'
