twig:
    default_path: '%kernel.project_dir%/templates'
    paths:
        '%kernel.project_dir%/email_assets/images': email-images
        '%kernel.project_dir%/email_assets/css': email-styles

when@test:
    twig:
        strict_variables: true
